package myartifact;

public class Consts {
	
	
	public static String msgConfig ="{\"transaction_id\":\"1620917717506\",\"detector_id\":\"609ce064d3da784f07a11b4e\",\"name\":\"Dummy 2\","
			+ "\"event\":{\"event_start_ts\": 1620917717506, \"event_type\":\"config_start\",\"event_id\":0},\"main_config\":{\"version\":1,\"name\":\"standard\",\"license\":\"sfsdfsdf\",\"description\":\"emulator standard config template\",\"default\":true,\"managementAccessInfoGrpc\":{\"ipAddress\":\"10.19.0.234\",\"tcpPort\":\"10000\"},\"netconfAccessInfo\":{\"serverIpAddress\":\"10.19.0.234\",\"serverTcpPort\":830,\"serverUser\":\"radware\",\"serverPassword\":\"12345\"},\"reportingInfo\":{\"reportIntervalSec\":2},\"telemetryInfo\":{\"interfaces\":[{\"_id\":\"609d2550f9be9810ef99a935\",\"name\":\"TenGigE0/0/0/1\",\"mode\":\"rx\"},{\"_id\":\"609d2550f9be98a73099a936\",\"name\":\"TenGigE0/0/0/2\",\"mode\":\"rx\"},{\"_id\":\"609d2550f9be98e53999a937\",\"name\":\"TenGigE0/0/0/3\",\"mode\":\"rx\"}],\"deletedInterfaces\":[],\"protocol\":\"GPB\",\"samplingRate\":5,\"exporterIpAddress\":\"10.19.0.234\",\"exporterPort\":5005},\"hardwareTemplate\":\"609c00c7d3da78f15ca10c5a\"},\"sec_config\":{\"detectionAlgorithms\":[{\"_id\":\"609c00c7d3da785b5fa10c5d\",\"id\":\"msd2\",\"name\":\"Behavioral TEID\",\"parameters\":[{\"_id\":\"609c00c7d3da78f096a10c5e\",\"type\":\"int\",\"id\":\"numberOfQuantiles\",\"name\":\"Number Of UE buckets\",\"value\":100},{\"_id\":\"609c00c7d3da78cfdca10c5f\",\"type\":\"int\",\"id\":\"minSamplesForLearning\",\"name\":\"Min active UEs per sec threshold\",\"value\":5},{\"_id\":\"609c00c7d3da780e4ea10c60\",\"type\":\"int\",\"id\":\"minFps\",\"name\":\"Min UE per sec threshold\",\"value\":1000},{\"_id\":\"609c00c7d3da78174fa10c61\",\"type\":\"float\",\"id\":\"minBwBps\",\"name\":\"Min BW threshold\",\"value\":0.01},{\"_id\":\"609c00c7d3da78887ba10c62\",\"type\":\"boolean\",\"id\":\"swapKey\",\"name\":\"Swap flow key\",\"value\":true},{\"_id\":\"609c00c7d3da78c9a1a10c63\",\"type\":\"int\",\"id\":\"quietTime\",\"name\":\"Inactivity before re-learning\",\"value\":10},{\"_id\":\"609c00c7d3da781f1ea10c64\",\"type\":\"float\",\"id\":\"attackStartThreshold\",\"value\":2,\"name\":\"Bps attack threshold\"},{\"_id\":\"609c00c7d3da78cb67a10c65\",\"type\":\"float\",\"id\":\"attackStartThresholdPps\",\"value\":2,\"name\":\"Pps attack threshold\"},{\"_id\":\"609c00c7d3da7836b1a10c66\",\"type\":\"float\",\"id\":\"attackEndThreshold\",\"value\":1.5,\"name\":\"Bps attack end threshold\"},{\"_id\":\"609c00c7d3da7858dea10c67\",\"type\":\"float\",\"id\":\"attackEndThresholdPps\",\"value\":1.5,\"name\":\"Pps attack end threshold\"},{\"_id\":\"609c00c7d3da783799a10c68\",\"type\":\"int\",\"id\":\"attackDetectionInterval\",\"value\":2,\"name\":\"Bps attack start interval\"},{\"_id\":\"609c00c7d3da782ccea10c69\",\"type\":\"int\",\"id\":\"attackDetectionIntervalPps\",\"value\":2,\"name\":\"Pps attack start interval\"},{\"_id\":\"609c00c7d3da782f12a10c6a\",\"type\":\"float\",\"id\":\"minBw\",\"value\":0.005,\"name\":\"Bps attack detectable min load\"},{\"_id\":\"609c00c7d3da78ecf7a10c6b\",\"type\":\"float\",\"id\":\"minKpps\",\"value\":1,\"name\":\"Pps attack detectable min load\"},{\"_id\":\"609c00c7d3da7850aea10c6c\",\"type\":\"int\",\"id\":\"singleAttackerMinBw\",\"value\":1,\"name\":\"Bps UE detectable min load\"},{\"_id\":\"609c00c7d3da788721a10c6d\",\"type\":\"float\",\"id\":\"singleAttackerMinKpps\",\"value\":1,\"name\":\"Pps UE detectable min load\"}]},{\"_id\":\"609c00c7d3da78476ba10c6e\",\"id\":\"thdsrc\",\"name\":\"Threshold TEID\",\"parameters\":[{\"_id\":\"609c00c7d3da781844a10c6f\",\"type\":\"float\",\"id\":\"attackHighWater1\",\"name\":\"Attack High Water Mark\",\"value\":0.5},{\"_id\":\"609c00c7d3da785ce7a10c70\",\"type\":\"float\",\"id\":\"attackLowWater2\",\"name\":\"Attack Low Water Mark\",\"value\":0.4},{\"_id\":\"609c00c7d3da78357fa10c71\",\"type\":\"int\",\"id\":\"aboveHighIntervals\",\"name\":\"Above High Interval\",\"value\":5},{\"_id\":\"609c00c7d3da788a67a10c72\",\"type\":\"int\",\"id\":\"belowLowIntervals\",\"name\":\"Below Low Interval\",\"value\":5}]}],\"version\":1,\"name\":\"standard\",\"default\":true,\"attackEndDetection\":{\"attackEndGraceSec\":60,\"attackEndTelemetry\":\"peeping\",\"peepingRemovalIntervalSec\":1000},\"attackCharacterization\":{\"enabled\":true,\"characterizationIntervalSec\":3,\"characterizationAlgorithm\":\"byTuple\"},\"mitigation\":{\"method\":\"teid\",\"maxBlockedTEID\":500},\"hardwareTemplate\":\"609c00c7d3da78f15ca10c5a\"},\"hardware\":{\"interfaces\":[\"TenGigE0/0/0/0\",\"TenGigE0/0/0/1\",\"TenGigE0/0/0/2\",\"TenGigE0/0/0/3\",\"TenGigE0/0/0/4\",\"TenGigE0/0/0/5\",\"TenGigE0/0/0/6\",\"TenGigE0/0/0/7\",\"TenGigE0/0/0/8\",\"TenGigE0/0/0/9\",\"TenGigE0/0/0/10\",\"TenGigE0/0/0/11\",\"TenGigE0/0/0/12\",\"TenGigE0/0/0/13\",\"TenGigE0/0/0/14\",\"TenGigE0/0/0/15\",\"TenGigE0/0/0/16\",\"TenGigE0/0/0/17\",\"TenGigE0/0/0/18\",\"TenGigE0/0/0/19\",\"TenGigE0/0/0/20\",\"TenGigE0/0/0/21\",\"TenGigE0/0/0/22\",\"TenGigE0/0/0/23\",\"HundredGigE0/0/1/0\",\"HundredGigE0/0/1/1\",\"TwentyFiveGigE0/0/0/24\",\"TwentyFiveGigE0/0/0/25\",\"TwentyFiveGigE0/0/0/26\",\"TwentyFiveGigE0/0/0/27\",\"TwentyFiveGigE0/0/0/28\",\"TwentyFiveGigE0/0/0/29\",\"TwentyFiveGigE0/0/0/30\",\"TwentyFiveGigE0/0/0/31\"],\"version\":1,\"name\":\"emulator default\",\"cores\":8,\"memoryInMB\":8096,\"allocatedCores\":2,\"allocatedMemoryInMB\":1024,\"warningMemoryPercentage\":50,\"criticalMemoryPercentage\":80,\"warningCpuPercentage\":50,\"criticalCpuPercentage\":80,\"detectorMaxFPS\":120000,\"maxTelemtryPPS\":5000,\"maxTelemtryMBs\":10,\"deploySupport\":false,\"appStartSupport\":false,\"configSupport\":true,\"rpmSrc\":\"dpro-110276.rpm\",\"model\":\"609c00c7d3da7846b4a10c58\"}}"; 
	
	public static String msgConfig2 = "{\r\n"
			+ "	\"detector_id\": \"d99faf2b-d89f-40e2-8041-b68ed69424d9\",\r\n"
			+ "	\"transaction_id\": \"135\",\r\n"
			+"	\"name\": \"detector1\",\r\n"
			+ "	\"event\": {\r\n"
			+ "		\"event_type\": \"config_start\",\r\n"
			+ "		\"event_id\": \"0\",\r\n"
			+ "		\"event_start_ts\": 1613916292726\r\n"
			+ "	},\r\n"
			+ "	\"main_config\": {\r\n"
			+ "		\"_id\": \"602d57aa86b8916014740d1a\",\r\n"
			+ "		\"version\": \"1\",\r\n"
			+ "		\"name\": \"standard\",\r\n"
			+ "		\"modelName\": \"NCS540\",\r\n"
			+ "		\"description\": \"Cisco NCS540 standard config template\",\r\n"
			+ "		\"default\": true,\r\n"
			+ "		\"managementAccessInfoGrpc\": {\r\n"
			+ "			\"ipAddress\": \"10.19.0.150\",\r\n"
			+ "			\"tcpPort\": 10000\r\n"
			+ "		},\r\n"
			+ "		\"netconfAccessInfo\": {\r\n"
			+ "			\"serverIpAddress\": \"10.19.0.150\",\r\n"
			+ "			\"serverTcpPort\": 830,\r\n"
			+ "			\"serverUser\": \"radware\",\r\n"
			+ "			\"serverPassword\": \"radware\"\r\n"
			+ "		},\r\n"
			+ "		\"reportingInfo\": {\r\n"
			+ "			\"reportIntervalSec\": 3.0\r\n"
			+ "		},\r\n"
			+ "		\"telemetryInfo\": {\r\n"
			+ "			\"protocol\": \"GPB\",\r\n"
			+ "			\"samplingRate\": 10000.0,\r\n"
			+ "			\"exporterIpAddress\": \"10.19.0.150\",\r\n"
			+ "			\"exporterPort\": 5005,\r\n"
			+ "			\"interfaces\": [\r\n"
			+ "				{\r\n"
			+ "					\"name\": \"TenGigE0/0/0/1\",\r\n"
			+ "					\"mode\": \"rx\"\r\n"
			+ "				}\r\n"
			+ "			]\r\n"
			+ "		},\r\n"
			+ "		\"baseTemplateId\": \"602d57aa86b8916014740d1a\"\r\n"
			+ "	},\r\n"
			+ "	\"sec_config\": {\r\n"
			+ "		\"_id\": \"602d585586b8916014740d1c\",\r\n"
			+ "		\"version\": \"1\",\r\n"
			+ "		\"modelName\": \"NCS540\",\r\n"
			+ "		\"name\": \"standard\",\r\n"
			+ "		\"description\": \"Cisco NCS540 standard security template\",\r\n"
			+ "		\"default\": false,\r\n"
			+ "		\"detectionAlgorithms\": [\r\n"
			+ "			{\r\n"
			+ "				\"id\": \"msd2\",\r\n"
			+ "				\"name\": \"Behavioral TEID\",\r\n"
			+ "				\"parameters\": [\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"numberOfQuantiles\",\r\n"
			+ "						\"name\": \"Number Of UE buckets\",\r\n"
			+ "						\"value\": 100.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"minSamplesForLearning\",\r\n"
			+ "						\"name\": \"Minimal flows per UE during learnig\",\r\n"
			+ "						\"value\": 5.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"minFps\",\r\n"
			+ "						\"name\": \"Min Fps Threshold\",\r\n"
			+ "						\"value\": 1000.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"minBw\",\r\n"
			+ "						\"name\": \"Min Bw Detectable Attack (GBs)\",\r\n"
			+ "						\"value\": 0.001\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"minBwBps\",\r\n"
			+ "						\"name\": \"Min Bw Bps Threshold (GBs)\",\r\n"
			+ "						\"value\": 0.01\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"attackStartThreshold\",\r\n"
			+ "						\"name\": \"Attack Threshold (%)\",\r\n"
			+ "						\"value\": 2.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"float\",\r\n"
			+ "						\"id\": \"attackEndThreshold\",\r\n"
			+ "						\"name\": \"Attack End Threshold (%)\",\r\n"
			+ "						\"value\": 1.5\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"boolean\",\r\n"
			+ "						\"id\": \"swapKey\",\r\n"
			+ "						\"name\": \"Swap flow key\",\r\n"
			+ "						\"value\": true\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"quietTime\",\r\n"
			+ "						\"name\": \"Period -of quiet time to restart learning (s)\",\r\n"
			+ "						\"value\": 10.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"attackDetectionInterval\",\r\n"
			+ "						\"name\": \"Interval of continous traffic for attack start (s)\",\r\n"
			+ "						\"value\": 2.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"float\",\r\n"
			+ "						\"id\": \"singleAttackerMinBw\",\r\n"
			+ "						\"name\": \"Minimal BW for flagging for mitigation (MBs)\",\r\n"
			+ "						\"value\": 0.001\r\n"
			+ "					}\r\n"
			+ "				]\r\n"
			+ "			},\r\n"
			+ "			{\r\n"
			+ "				\"id\": \"thdsrc\",\r\n"
			+ "				\"name\": \"Threshold TEID\",\r\n"
			+ "				\"parameters\": [\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"float\",\r\n"
			+ "						\"id\": \"attackHighWater1\",\r\n"
			+ "						\"name\": \"Attack High Water Mark (GBs)\",\r\n"
			+ "						\"value\": 0.5\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"float\",\r\n"
			+ "						\"id\": \"attackLowWater2\",\r\n"
			+ "						\"name\": \"Attack Low Water Mark (GBs)\",\r\n"
			+ "						\"value\": 0.4\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"aboveHighIntervals\",\r\n"
			+ "						\"name\": \"Above High Interval (s)\",\r\n"
			+ "						\"value\": 5.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"belowLowIntervals\",\r\n"
			+ "						\"name\": \"Below Low Interval (s)\",\r\n"
			+ "						\"value\": 5.0\r\n"
			+ "					}\r\n"
			+ "				]\r\n"
			+ "			}"
			+ "		],\r\n"
			+ "		\"attackEndDetection\": {\r\n"
			+ "			\"attackEndGraceSec\": 1000.0,\r\n"
			+ "			\"attackEndTelemetry\": \"peeping\",\r\n"
			+ "			\"peepingRemovalIntervalSec\": 1000.0\r\n"
			+ "		},\r\n"
			+ "		\"attackCharacterization\": {\r\n"
			+ "			\"enabled\": \"true\",\r\n"
			+ "			\"characterizationIntervalSec\": 3.0,\r\n"
			+ "			\"characterizationAlgorithm\": \"byTuple\"\r\n"
			+ "		},\r\n"
			+ "		\"mitigation\": {\r\n"
			+ "			\"method\": \"teid\",\r\n"
			+ "			\"maxBlockedTEID\": 500.0\r\n"
			+ "		},\r\n"
			+ "		\"baseTemplateId\": \"602d585586b8916014740d1c\"\r\n"
			+ "	},\r\n"
			+ "	\"hardware\": {\r\n"
			+ "		\"_id\": {\r\n"
			+ "			\"$oid\": \"602d580a86b8916014740d1b\"\r\n"
			+ "		},\r\n"
			+ "		\"version\": \"1\",\r\n"
			+ "		\"modelName\": \"NCS540\",\r\n"
			+ "		\"description\": \"Cisco NCS540 Aggregation Router\",\r\n"
			+ "		\"cores\": 8.0,\r\n"
			+ "		\"memoryInMB\": 8096.0,\r\n"
			+ "		\"allocatedCores\": 2.0,\r\n"
			+ "		\"allocatedMemoryInMB\": 1024.0,\r\n"
			+ "		\"warninglMemoryPercentage\": 50.0,\r\n"
			+ "		\"criticalMemoryPercentage\": 80.0,\r\n"
			+ "		\"warninglCpuPercentage\": 50.0,\r\n"
			+ "		\"criticalCpuPercentage\": 80.0,\r\n"
			+ "		\"detectorMaxFPS\": 120000.0,\r\n"
			+ "		\"deploySupport\": \"true\",\r\n"
			+ "		\"interfaces\": [\r\n"
			+ "			\"TenGigE0/0/0/0\",\r\n"
			+ "			\"TenGigE0/0/0/1\",\r\n"
			+ "			\"TenGigE0/0/0/2\",\r\n"
			+ "			\"TenGigE0/0/0/4\",\r\n"
			+ "			\"TenGigE0/0/0/5\",\r\n"
			+ "			\"TenGigE0/0/0/6\",\r\n"
			+ "			\"TenGigE0/0/0/7\",\r\n"
			+ "			\"TenGigE0/0/0/8\",\r\n"
			+ "			\"TenGigE0/0/0/9\",\r\n"
			+ "			\"TenGigE0/0/0/10\",\r\n"
			+ "			\"TenGigE0/0/0/11\",\r\n"
			+ "			\"TenGigE0/0/0/12\",\r\n"
			+ "			\"TenGigE0/0/0/13\",\r\n"
			+ "			\"TenGigE0/0/0/14\",\r\n"
			+ "			\"TenGigE0/0/0/15\",\r\n"
			+ "			\"TenGigE0/0/0/16\",\r\n"
			+ "			\"TenGigE0/0/0/17\",\r\n"
			+ "			\"TenGigE0/0/0/18\",\r\n"
			+ "			\"TenGigE0/0/0/19\",\r\n"
			+ "			\"TenGigE0/0/0/20\",\r\n"
			+ "			\"TenGigE0/0/0/21\",\r\n"
			+ "			\"TenGigE0/0/0/22\",\r\n"
			+ "			\"TenGigE0/0/0/23\",\r\n"
			+ "			\"HundredGigE0/0/1/0\",\r\n"
			+ "			\"HundredGigE0/0/1/1\",\r\n"
			+ "			\"GigabitEthernet0/0/0/3\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/24\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/25\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/26\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/27\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/28\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/29\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/30\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/31\"\r\n"
			+ "		]\r\n"
			+ "	}\r\n"
			+ "}";
	
	
	
	
	public static String msgConfigReal = "{\r\n"
			+ "	\"detector_id\": \"993ace1c-8237-43c2-8483-cdc16473deaa\",\r\n"
			+ "	\"transaction_id\": \"135\",\r\n"
			+"	\"name\": \"detector1\",\r\n"
			+ "	\"event\": {\r\n"
			+ "		\"event_type\": \"config_start\",\r\n"
			+ "		\"event_id\": \"0\",\r\n"
			+ "		\"event_start_ts\": 1613916292726\r\n"
			+ "	},\r\n"
			+ "	\"main_config\": {\r\n"
			+ "		\"_id\": \"602d57aa86b8916014740d1a\",\r\n"
			+ "		\"version\": \"1\",\r\n"
			+ "		\"name\": \"standard\",\r\n"
			+ "		\"modelName\": \"NCS540\",\r\n"
			+ "		\"description\": \"Cisco NCS540 standard config template\",\r\n"
			+ "		\"default\": true,\r\n"
			+ "		\"managementAccessInfoGrpc\": {\r\n"
			+ "			\"ipAddress\": \"10.19.0.20\",\r\n"
			+ "			\"tcpPort\": 10000\r\n"
			+ "		},\r\n"
			+ "		\"netconfAccessInfo\": {\r\n"
			+ "			\"serverIpAddress\": \"17.1.1.2\",\r\n"
			+ "			\"serverTcpPort\": 830,\r\n"
			+ "			\"serverUser\": \"radware\",\r\n"
			+ "			\"serverPassword\": \"radware\"\r\n"
			+ "		},\r\n"
			+ "		\"reportingInfo\": {\r\n"
			+ "			\"reportIntervalSec\": 3.0\r\n"
			+ "		},\r\n"
			+ "		\"telemetryInfo\": {\r\n"
			+ "			\"protocol\": \"GPB\",\r\n"
			+ "			\"samplingRate\": 10000.0,\r\n"
			+ "			\"exporterIpAddress\": \"15.1.1.2\",\r\n"
			+ "			\"exporterPort\": 5005,\r\n"
			+ "			\"interfaces\": [\r\n"
			+ "				{\r\n"
			+ "					\"name\": \"TenGigE0/0/0/1\",\r\n"
			+ "					\"mode\": \"rx\"\r\n"
			+ "				}\r\n"
			+ "			]\r\n"
			+ "		},\r\n"
			+ "		\"baseTemplateId\": \"602d57aa86b8916014740d1a\"\r\n"
			+ "	},\r\n"
			+ "	\"sec_config\": {\r\n"
			+ "		\"_id\": \"602d585586b8916014740d1c\",\r\n"
			+ "		\"version\": \"1\",\r\n"
			+ "		\"modelName\": \"NCS540\",\r\n"
			+ "		\"name\": \"standard\",\r\n"
			+ "		\"description\": \"Cisco NCS540 standard security template\",\r\n"
			+ "		\"default\": false,\r\n"
			+ "		\"detectionAlgorithms\": [\r\n"
			+ "			{\r\n"
			+ "				\"id\": \"msd2\",\r\n"
			+ "				\"name\": \"Behavioral TEID\",\r\n"
			+ "				\"parameters\": [\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"numberOfQuantiles\",\r\n"
			+ "						\"name\": \"Number Of UE buckets\",\r\n"
			+ "						\"value\": 100.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"minSamplesForLearning\",\r\n"
			+ "						\"name\": \"Minimal flows per UE during learnig\",\r\n"
			+ "						\"value\": 5.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"minFps\",\r\n"
			+ "						\"name\": \"Min Fps Threshold\",\r\n"
			+ "						\"value\": 1000.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"minBw\",\r\n"
			+ "						\"name\": \"Min Bw Detectable Attack (GBs)\",\r\n"
			+ "						\"value\": 0.001\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"minBwBps\",\r\n"
			+ "						\"name\": \"Min Bw Bps Threshold (GBs)\",\r\n"
			+ "						\"value\": 0.01\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"attackStartThreshold\",\r\n"
			+ "						\"name\": \"Attack Threshold (%)\",\r\n"
			+ "						\"value\": 2.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"float\",\r\n"
			+ "						\"id\": \"attackEndThreshold\",\r\n"
			+ "						\"name\": \"Attack End Threshold (%)\",\r\n"
			+ "						\"value\": 1.5\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"boolean\",\r\n"
			+ "						\"id\": \"swapKey\",\r\n"
			+ "						\"name\": \"Swap flow key\",\r\n"
			+ "						\"value\": true\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"quietTime\",\r\n"
			+ "						\"name\": \"Period -of quiet time to restart learning (s)\",\r\n"
			+ "						\"value\": 10.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"attackDetectionInterval\",\r\n"
			+ "						\"name\": \"Interval of continous traffic for attack start (s)\",\r\n"
			+ "						\"value\": 2.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"float\",\r\n"
			+ "						\"id\": \"singleAttackerMinBw\",\r\n"
			+ "						\"name\": \"Minimal BW for flagging for mitigation (MBs)\",\r\n"
			+ "						\"value\": 0.001\r\n"
			+ "					}\r\n"
			+ "				]\r\n"
			+ "			},\r\n"
			+ "			{\r\n"
			+ "				\"id\": \"thdsrc\",\r\n"
			+ "				\"name\": \"Threshold TEID\",\r\n"
			+ "				\"parameters\": [\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"float\",\r\n"
			+ "						\"id\": \"attackHighWater1\",\r\n"
			+ "						\"name\": \"Attack High Water Mark (GBs)\",\r\n"
			+ "						\"value\": 0.5\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"float\",\r\n"
			+ "						\"id\": \"attackLowWater2\",\r\n"
			+ "						\"name\": \"Attack Low Water Mark (GBs)\",\r\n"
			+ "						\"value\": 0.4\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"aboveHighIntervals\",\r\n"
			+ "						\"name\": \"Above High Interval (s)\",\r\n"
			+ "						\"value\": 5.0\r\n"
			+ "					},\r\n"
			+ "					{\r\n"
			+ "						\"type\": \"int\",\r\n"
			+ "						\"id\": \"belowLowIntervals\",\r\n"
			+ "						\"name\": \"Below Low Interval (s)\",\r\n"
			+ "						\"value\": 5.0\r\n"
			+ "					}\r\n"
			+ "				]\r\n"
			+ "			}"
			+ "		],\r\n"
			+ "		\"attackEndDetection\": {\r\n"
			+ "			\"attackEndGraceSec\": 1000.0,\r\n"
			+ "			\"attackEndTelemetry\": \"peeping\",\r\n"
			+ "			\"peepingRemovalIntervalSec\": 1000.0\r\n"
			+ "		},\r\n"
			+ "		\"attackCharacterization\": {\r\n"
			+ "			\"enabled\": \"true\",\r\n"
			+ "			\"characterizationIntervalSec\": 3.0,\r\n"
			+ "			\"characterizationAlgorithm\": \"byTuple\"\r\n"
			+ "		},\r\n"
			+ "		\"mitigation\": {\r\n"
			+ "			\"method\": \"teid\",\r\n"
			+ "			\"maxBlockedTEID\": 500.0\r\n"
			+ "		},\r\n"
			+ "		\"baseTemplateId\": \"602d585586b8916014740d1c\"\r\n"
			+ "	},\r\n"
			+ "	\"hardware\": {\r\n"
			+ "		\"_id\": {\r\n"
			+ "			\"$oid\": \"602d580a86b8916014740d1b\"\r\n"
			+ "		},\r\n"
			+ "		\"version\": \"1\",\r\n"
			+ "		\"modelName\": \"NCS540\",\r\n"
			+ "		\"description\": \"Cisco NCS540 Aggregation Router\",\r\n"
			+ "		\"cores\": 8.0,\r\n"
			+ "		\"memoryInMB\": 8096.0,\r\n"
			+ "		\"allocatedCores\": 2.0,\r\n"
			+ "		\"allocatedMemoryInMB\": 1024.0,\r\n"
			+ "		\"warninglMemoryPercentage\": 50.0,\r\n"
			+ "		\"criticalMemoryPercentage\": 80.0,\r\n"
			+ "		\"warninglCpuPercentage\": 50.0,\r\n"
			+ "		\"criticalCpuPercentage\": 80.0,\r\n"
			+ "		\"detectorMaxFPS\": 120000.0,\r\n"
			+ "		\"deploySupport\": \"true\",\r\n"
			+ "		\"interfaces\": [\r\n"
			+ "			\"TenGigE0/0/0/0\",\r\n"
			+ "			\"TenGigE0/0/0/1\",\r\n"
			+ "			\"TenGigE0/0/0/2\",\r\n"
			+ "			\"TenGigE0/0/0/4\",\r\n"
			+ "			\"TenGigE0/0/0/5\",\r\n"
			+ "			\"TenGigE0/0/0/6\",\r\n"
			+ "			\"TenGigE0/0/0/7\",\r\n"
			+ "			\"TenGigE0/0/0/8\",\r\n"
			+ "			\"TenGigE0/0/0/9\",\r\n"
			+ "			\"TenGigE0/0/0/10\",\r\n"
			+ "			\"TenGigE0/0/0/11\",\r\n"
			+ "			\"TenGigE0/0/0/12\",\r\n"
			+ "			\"TenGigE0/0/0/13\",\r\n"
			+ "			\"TenGigE0/0/0/14\",\r\n"
			+ "			\"TenGigE0/0/0/15\",\r\n"
			+ "			\"TenGigE0/0/0/16\",\r\n"
			+ "			\"TenGigE0/0/0/17\",\r\n"
			+ "			\"TenGigE0/0/0/18\",\r\n"
			+ "			\"TenGigE0/0/0/19\",\r\n"
			+ "			\"TenGigE0/0/0/20\",\r\n"
			+ "			\"TenGigE0/0/0/21\",\r\n"
			+ "			\"TenGigE0/0/0/22\",\r\n"
			+ "			\"TenGigE0/0/0/23\",\r\n"
			+ "			\"HundredGigE0/0/1/0\",\r\n"
			+ "			\"HundredGigE0/0/1/1\",\r\n"
			+ "			\"GigabitEthernet0/0/0/3\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/24\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/25\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/26\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/27\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/28\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/29\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/30\",\r\n"
			+ "			\"TwentyFiveGigE0/0/0/31\"\r\n"
			+ "		]\r\n"
			+ "	}\r\n"
			+ "}";
	
	
	
	
	
}
//GBP,NFV9